apiVersion: v1
kind: Pod
metadata:
  name: node-exporter
  namespace: monitor
  labels:
    name: node-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
    prometheus.io/param_measurement: "node-test"
spec:
  tolerations:
  - effect: NoSchedule
    operator: Exists
  hostPID: true
  hostIPC: true
  hostNetwork: true
  containers:
  - name: node-exporter
    image: prom/node-exporter:v0.16.0
    ports:
    - containerPort: 9100
    securityContext:
      privileged: true
    args:
    - --path.procfs
    - /host/proc
    - --path.sysfs
    - /host/sys
    - --collector.filesystem.ignored-mount-points
    - '"^/(sys|proc|dev|host|etc)($|/)"'
    - --collector.systemd
    - --collector.systemd.unit-whitelist=(docker|sshd|kubelet).service
   # - '"^/(sys|proc|dev|host|etc)($|/)"'
    volumeMounts:
    - name: dev
      mountPath: /host/dev
    - name: proc
      mountPath: /host/proc
    - name: sys
      mountPath: /host/sys
    - name: rootfs
      mountPath: /rootfs
  volumes:
    - name: proc
      hostPath:
        path: /proc
    - name: dev
      hostPath:
        path: /dev
    - name: sys
      hostPath:
        path: /sys
    - name: rootfs
      hostPath:
        path: /

